// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.57.4";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated." }],
    isError: true
  };
}

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Get the signed-in user's public profile on The Forge (display name, bio, avatar, verification status).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("display_name, bio, avatar_url, location, website, is_verified, is_identity_verified, created_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No profile found for this account." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/get-my-creator-stats.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
var get_my_creator_stats_default = defineTool2({
  name: "get_my_creator_stats",
  title: "Get my creator stats",
  description: "Get the signed-in creator's key stats on The Forge: stage name, subscription price, subscriber count, published content count and total earnings.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("get_my_creator_full").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "This account is not a creator account." }] };
    const creator = {
      id: data.id,
      stage_name: data.stage_name,
      category: data.category,
      subscription_price: data.subscription_price,
      currency: data.currency,
      total_subscribers: data.total_subscribers,
      total_content: data.total_content,
      total_earnings: data.total_earnings,
      is_paused: data.is_paused,
      is_featured: data.is_featured
    };
    return {
      content: [{ type: "text", text: JSON.stringify(creator) }],
      structuredContent: { creator }
    };
  }
});

// src/lib/mcp/tools/list-my-content.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";
var list_my_content_default = defineTool3({
  name: "list_my_content",
  title: "List my content",
  description: "List the signed-in creator's content items on The Forge with title, type, price, status and engagement counters.",
  inputSchema: {
    limit: z.number().int().optional().describe("Maximum number of items to return (default 20, max 100)."),
    status: z.enum(["draft", "published", "archived"]).optional().describe("Filter by publication status.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data: creator, error: creatorError } = await supabase.from("creators").select("id").eq("user_id", ctx.getUserId()).maybeSingle();
    if (creatorError) return { content: [{ type: "text", text: creatorError.message }], isError: true };
    if (!creator) return { content: [{ type: "text", text: "This account is not a creator account." }] };
    const max = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabase.from("content").select("id, title, content_type, is_premium, price, status, view_count, like_count, created_at").eq("creator_id", creator.id).order("created_at", { ascending: false }).limit(max);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-subscriptions.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var list_my_subscriptions_default = defineTool4({
  name: "list_my_subscriptions",
  title: "List my subscriptions",
  description: "List the subscriptions of the signed-in account on The Forge — the creators they subscribe to, plus subscriptions received when the account is a creator.",
  inputSchema: {
    status: z2.enum(["active", "expired", "canceled"]).optional().describe("Filter by subscription status."),
    limit: z2.number().int().optional().describe("Maximum number of subscriptions to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const max = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabase.from("subscriptions").select("id, creator_id, subscriber_id, status, price, currency, start_date, end_date, auto_renew, created_at").order("created_at", { ascending: false }).limit(max);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { subscriptions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-notifications.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_notifications_default = defineTool5({
  name: "list_my_notifications",
  title: "List my notifications",
  description: "List the signed-in user's recent notifications on The Forge (new subscribers, tips, messages, sales).",
  inputSchema: {
    unread_only: z3.boolean().optional().describe("Only return unread notifications."),
    limit: z3.number().int().optional().describe("Maximum number of notifications to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ unread_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const max = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabase.from("notifications").select("id, type, title, message, read, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(max);
    if (unread_only) query = query.eq("read", false);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { notifications: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-live-streams.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_my_live_streams_default = defineTool6({
  name: "list_my_live_streams",
  title: "List my live streams",
  description: "List the signed-in creator's live streams on The Forge (scheduled, live and ended) with viewer counts.",
  inputSchema: {
    status: z4.enum(["scheduled", "live", "ended"]).optional().describe("Filter by stream status."),
    limit: z4.number().int().optional().describe("Maximum number of streams to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data: creator, error: creatorError } = await supabase.from("creators").select("id").eq("user_id", ctx.getUserId()).maybeSingle();
    if (creatorError) return { content: [{ type: "text", text: creatorError.message }], isError: true };
    if (!creator) return { content: [{ type: "text", text: "This account is not a creator account." }] };
    const max = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabase.from("live_streams").select("id, title, status, is_premium, price, scheduled_at, started_at, ended_at, viewer_count, peak_viewer_count").eq("creator_id", creator.id).order("created_at", { ascending: false }).limit(max);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { streams: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "usjxcgauyvdocngfkhys";
var mcp_default = defineMcp({
  name: "fan-forge-global",
  title: "fan-forge-global",
  version: "0.1.0",
  instructions: "Tools for The Forge, a creator subscription platform. All tools act as the signed-in user: read their profile, creator stats, content library, subscriptions, live streams and notifications.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_my_profile_default,
    get_my_creator_stats_default,
    list_my_content_default,
    list_my_subscriptions_default,
    list_my_notifications_default,
    list_my_live_streams_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
