// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://usjxcgauyvdocngfkhys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzanhjZ2F1eXZkb2NuZ2ZraHlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMjAyMTQsImV4cCI6MjA3Mzc5NjIxNH0.ctjjyUwQ1RE49ij3z1vSL85lJoWopV2L_fGuC2YH6RQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});